
import React from 'react';

export const GIFT_MESSAGES = [
  "Merry Christmas! May your holidays be filled with joy.",
  "Wishing you a season of peace and love.",
  "Warmest wishes for a wonderful Christmas day!",
  "May your heart be light and spirit bright!",
  "Cheers to a season of giving and gratitude!",
  "Deck the halls with boughs of holly!",
  "Ho Ho Ho! Santa is on his way!",
  "May Christmas magic fill your home and heart.",
  "Wishing you health, happiness, and festive cheer!",
  "Christmas is a state of mind, not a season.",
  "Family is the best gift around the tree.",
  "Peace on earth begins with a kind heart.",
  "Keep Christmas in your heart all year long.",
  "Christmas makes everything softer and more beautiful.",
  "Cherish the special moments spent with loved ones.",
  "Simple love is the true meaning of Christmas.",
  "Kindle the fire of hospitality this holiday season.",
  "Time and love are the best holiday ingredients.",
  "Celebrate the joy of a warm, happy home.",
  "The spirit of Christmas is love and generosity.",
  "Build bridges of love this festive season.",
  "Christmas memories dance like snowflakes in the wind.",
  "Think of others and feed your soul today.",
  "Keep the holiday beautiful with thoughts of kindness.",
  "A small gift from someone dear brings joy.",
  "Best wishes for a bright and happy year!",
  "Christmas isn't a season, it's a warm feeling.",
  "Share generosity and gratitude with everyone you meet.",
  "Love is more important than any expensive gift.",
  "Reflect on the important things this holiday season.",
  "Never stop searching the skies on Christmas Eve.",
  "You don't hear Christmas magic, you feel it.",
  "Twas the night before Christmas, silent and still.",
  "Always love the giver more than the gift.",
  "Christmas is doing something extra for someone else.",
  "Put love into every gift you give today.",
  "At Christmas, all roads lead back home.",
  "May your home be filled with quiet laughter.",
  "Open your heart to great possibilities this year.",
  "Christmas keeps the memories of our innocence alive.",
  "Christmas is a sweet candy for the soul.",
  "Brighten lives with the magic of the holidays.",
  "Give the light of love to those in need.",
  "Nothing is cozier than a lit Christmas tree.",
  "Honor Christmas in your heart every single day.",
  "Christmas is the glue that keeps us together.",
  "Christmas Eve wraps around you like a shawl.",
  "The world stays young at heart during Christmas.",
  "May you have the gifts of peace and hope.",
  "Christmas is found in the heart, not under trees.",
  "Christmas is tenderness for the past and hope.",
  "Celebrate the joy of family united in love.",
  "Share your blessings to make the season white.",
  "Christmas is the day holding all time together.",
  "A good conscience is a continuous Christmas feast.",
  "The word Christmas brings joy to every heart.",
  "Every time we give love, it is Christmas.",
  "Cherish peace and goodwill toward all people.",
  "Sound the trumpet of joy and festive rebirth!",
  "Kindle the flame of charity in your heart.",
  "Listen to the happy sound of Christmas bells.",
  "May sparkle and joy fill your heart today.",
  "I’m dreaming of a beautiful, white Christmas.",
  "Celebrate the love that surrounds you this year.",
  "May your holiday sparkle with love and laughter.",
  "There is no gift greater than true love.",
  "Wishing you a day full of happy surprises!",
  "Fill your home with the songs of Christmas.",
  "Save Santa the trip and be extra naughty!",
  "Sugar and spice make the holiday very nice.",
  "Find many reasons to smile this Christmas day.",
  "Sending warm hugs and lots of Christmas cheer.",
  "Make memories that will last a whole lifetime.",
  "May the holiday season bring you many blessings.",
  "Wishing you a very cozy and calm Christmas.",
  "Feel like a kid again on Christmas morning.",
  "Carry a piece of home in your heart.",
  "Sharing the holiday with you is my gift.",
  "May your stockings be full of joyful treats.",
  "Peace, love, and joy to you and yours.",
  "Have a very Merry Christmas and happy Year.",
  "May the magic of the season stay always.",
  "Be grateful for the wonderful people you know.",
  "Have yourself a very merry little Christmas.",
  "Stars shine brighter on this special Christmas Eve.",
  "Let the holiday spirit warm your entire soul.",
  "You make my life bright every single day.",
  "Fill your heart with the wonder of Christmas.",
  "Sending holiday wishes from across the many miles.",
  "May your Christmas be sweet as candy canes.",
  "Wishing you a season of light and laughter.",
  "Find peace in the quiet holiday moments.",
  "Celebrate the wonder of this festive season.",
  "May your day be merry and very bright.",
  "May your holiday be blessed with pure happiness.",
  "The spirit of Christmas is the greatest gift.",
  "Joy to the world and peace to all.",
  "Believe in the magic of the holiday season.",
  "May your heart be full of Christmas joy.",
  "Wishing you a magical and merry Christmas time!"
];

export const COLORS = {
  christmasRed: '#C41E3A',
  christmasGreen: '#165B33',
  christmasGold: '#FFD700',
  christmasWhite: '#F8F9FA',
  deepBlue: '#050a14'
};
